### ISSUE TITLE
Question: How to run Jupiter?

### ISSUE THREAD

**Issue by MarekPesta** [andrescv/Jupiter#28]
Hello!

I am new in the RISC V community and I want to create some project with the RISC V Core. I was trying to run Jupiter on Ubuntu 18.04.3 LTS but it did not work. I would like to use Jupiter to learn more about RISC V but I do not know how to run it correctly. I was wondering if there is a possibility to create a little guide/tutorial how to run Jupiter correctly? Of course if it wouldn't be a problem for you.

**Comment by andrescv** [comment]
Hi @MarekPesta !

Thanks for your question, if you want to run Jupiter in Ubuntu you need to do the following:

1. Download de app image from [here](https://github.com/andrescv/Jupiter/releases/download/v3.0/Jupiter-3.0-linux.zip)
2. Unzip the file
3. In a terminal:

```shell
./image/bin/jupiter # for GUI mode
./image/bin/jupiter [options] <files> # for CLI mode
```

I just recently add this instructions in the README file :100: 

If you encounter any problems, please let me know. Thank you for using Jupiter !

**Comment by MarekPesta** [comment]
Thank you, everything works!
