### ISSUE TITLE
Assembler directives errors

### ISSUE THREAD

**Issue by MarekPesta** [andrescv/Jupiter#29]
Hi!

I’m using pure RV32I Toolchain instaleld as described here: [link](https://github.com/cliffordwolf/picorv32#building-a-pure-rv32i-toolchain ).

I wrote a simple C program:

![image](https://user-images.githubusercontent.com/54101971/63282717-bb5cd780-c2af-11e9-9ddb-3fc04641d5e3.png)

Using mentioned RV32I Toolchain I generated .s file. I wanted to simulate this assembler code in Jupiter but I have some errors (errors that occured are commented in the  line they are related to):

![image](https://user-images.githubusercontent.com/54101971/63282751-cf083e00-c2af-11e9-9dff-c906a7d944ee.png)

Following the RISC-V Assembly Programmer's Manual: [link](https://github.com/riscv/riscv-asm-manual/blob/master/riscv-asm.md#pseudo-ops)
directives that are used in my code should be fine.

**Comment by andrescv** [comment]
Hi !

The RISC-V toolchain should not be used with Jupiter because the C compiler generates directives not supported (.option, .size, .ident) by Jupiter and other features like numeric labels.

**Comment by MarekPesta** [comment]
OK, thank you for your answer.
