### ISSUE TITLE
Questions about building project

### ISSUE THREAD

**Issue by ybharatu** [andrescv/Jupiter#32]
Jupiter has been great. It is very intuitive and powerful. 

Is there a way you can add build instructions for this project? I am new to using Gradle and I have had issues trying to run the application. I wanted to try experiment making scripts. 

Either way, I appreciate the work you put in. I am new to RISC V and this has let me obtain a better understanding.

**Comment by andrescv** [comment]
Hi @ybharatu!

Im really glad to know that this project is helping you in some way. With respect to your request, sure, I will put those instructions in the docs page, for now the page is a little bit incomplete but soon will be more detailed and useful.

**Comment by ybharatu** [comment]
Thank you. I was able to build it from source.
